### ISSUE TITLE
ASK: How to detect if one of the action toolbar clicked?

### ISSUE THREAD

**Issue by user14045** [wxik/react-native-rich-editor#55]
Hi, I'm using react-native-pell-rich-editor@1.0.6. Is there any way to detect if user just click one of the action provided in the list of action passed to the RichToolbar? My intention is I want to invoke some function when user click one of the action.

**Comment by wxik** [comment]
Try registerToolbar

**Comment by wxik** [comment]
#50

**Comment by blitzmohit** [comment]
Thanks @stulip I do see the toolbar item being called in the new example.

Would it possible to trigger the action functionality on the selected text ?

For example on clicking bold button it logs `Toolbar click, selected items (insert end callback): ["bold"]`, can I somehow call the action.setBold on the selectedText.

**Comment by stulip** [comment]
Thanks for @blitzmohit discovering

This is a bug that appears to fix the focus problem. I hurry to fix it.

**Comment by blitzmohit** [comment]
Thank you for acknowledging & fixing the issue @stulip , I see the version on master is executing the action on selection. 

I see some handling for actions.heading1 etc in RichTool.js but can't seem to follow how that is made available to a user. 

If I wanted to turn on just heading1 and heading2 do I need to create a customAction still ? If so could you provide an example on how it would look like since it will need to get the selectedText.

Really appreciate all your efforts in creating and maintaining this library.

**Comment by stulip** [comment]
@blitzmohit  

Please refer to master branch example or [Online Example](https://wxik.github.io/react-native-rich-editor/web)
